name: Bookmarklet Generator
description: Automatically generates a bookmarklet link from JavaScript and updates a target HTML file.
author: Your Name <your-email@example.com>
inputs:
  source-js-file:
    description: Path to the source JavaScript file.
    required: true
    default: src/bookmarklet.js
  target-html-file:
    description: Path to the target HTML file where the bookmarklet link is updated.
    required: true
    default: index.html
  target-element-id:
    description: ID of the link element in the target HTML file to update.
    required: true
    default: target
  commit-message:
    description: Commit message for the update.
    required: true
    default: Update bookmarklet link
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate Bookmarklet
      run: |
        if [ ! -f "${{ inputs.source-js-file }}" ]; then
          echo "Source file not found: ${{ inputs.source-js-file }}"
          exit 1
        fi
        if [ ! -f "${{ inputs.target-html-file }}" ]; then
          echo "Target HTML file not found: ${{ inputs.target-html-file }}"
          exit 1
        fi
        node << 'EOF'
          const fs = require('fs');
          const sourceFile = process.env.SOURCE_JS_FILE || '${{ inputs.source-js-file }}';
          const targetFile = process.env.TARGET_HTML_FILE || '${{ inputs.target-html-file }}';
          const targetElementId = process.env.TARGET_ELEMENT_ID || '${{ inputs.target-element-id }}';

          const jsContent = fs.readFileSync(sourceFile, 'utf-8').trim();
          let processedCode = jsContent.startsWith('(function') ? jsContent : `(function(){${jsContent}})();`;
          const bookmarklet = 'javascript:' + encodeURIComponent(processedCode);

          const html = fs.readFileSync(targetFile, 'utf-8');
          const updatedHtml = html.replace(
            new RegExp(`<a[^>]+id="${targetElementId}"[^>]*href="[^"]*"`, 'i'),
            `<a id="${targetElementId}" href="${bookmarklet}"`
          );

          fs.writeFileSync(targetFile, updatedHtml, 'utf-8');
        EOF

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.target-html-file }}
        git diff-index --quiet HEAD || git commit -m "${{ inputs.commit-message }}"
        git push
branding:
  icon: bookmark
  color: blue
